CREATE TABLE asociacion_autoridad(
	aso_id SERIAL,
	aso_nombre VARCHAR(150),
	aso_texto TEXT,
	PRIMARY KEY(aso_id)
);

INSERT INTO asociacion_autoridad (aso_nombre,aso_texto) VALUES	
	('ASOCIACION DE CABILDOS Y AUTORIDADES TRADICIONALES DEL CONSEJO INDÍGENA MAYOR DEL PUEBLO MURUI (CIMPUM)','Nuestro Moo Añ+raima Padre Creador quien se sienta en el trono a pensar la creación de la humanidad, forma a su hijo Moo Buinaima y este le entrega la palabra a Koreg+ Buinaima quien transmite este poder a los cuatro Sabios del Pueblo Múrui Yua Buinaima, Z+k+da Buinaima, Noin+ Buinaima y Menigu+ Buinaima. Estos seres espirituales manejan la palabra con la cual capacitan a las nuevas generaciones para el manejo del Territorio y el Gobierno Tradicional.'),
	('ASOCIACION DE CABILDOS INDIGENAS DE CALDAS  "ACICAL"', 'La ACICAL tiene por objeto el desarrollo integral de las comunidades indígenas representadas en los cabildos del departamento de Caldas, mediante la celebración de convenios, contratos y proyectos con entidades públicas y privadas del orden nacional e internacional, que hagan parte de sus iniciativas colectivas, planes de vida, usos y costumbres, buscando la preservación de su identidad, el fortalecimiento de la autonomía y la autodeterminación.'),
	('ASOCIACION DE CABILDOS UKAWE´S  X NASA CXHAB', 'Somos una organización que busca el respeto y garantías a nuestro derecho a la vida y a la participación política, que están siendo vulnerados por  amenazas e intimidaciones a líderes y lideresas del sector indígena y campesino de Caldono, quienes, en un legítimo ejercicio y pacto de unidad comunitaria, estamos avanzando en un nuevo proyecto político que nos permita mantener la unidad, participación, transparencia, equidad y justicia social.'),
	('ASOCIACION DE AUTORIDADES TRADICIONALES U´WA', 'La ASOUWA (Asociación del pueblo U’wa) Esta organizacion busca crear estrategias de defensa de los derechos hacia afuera, partiendo de la identidad social y territorial y fortaleciendo l ainterculturalidad del pueblo, luchando por la recuperación de sus territorios, exigiendo el cumplimiento de los Derechos especiales indígenas, los civiles y los Humanos y denunciando las violaciones a éstos'),
	('ASOCIACION DE AUTORIDADES INDIGENAS DE (LOS PASTOS NARIÑO)', 'Somos una entidad de derecho público con personería jurídica, patrimonio propio y autonomía administrativa; se sujeta al sistema normativo del derecho mayor.'),
	('ASOCIACION DE AUTORIDADES TRADICIONALES YUKPAS SERRANIA DEL PERIJA  (SEKEIMU)', 'Esta organización tiene por objetivo el desarrollo integral de las comunidades indígenas la lucha por la recuperación de sus territorios, exigiendo el cumplimiento de los Derechos especiales indígenas, buscando la preservación de su identidad, el fortalecimiento de la autonomía y la autodeterminación.'),
	('ASOCIACION DE CABILDOS Y AUTORIDADES INDIGENAS DE LA REGION DEL TOMO (PALAMEKU)', 'Esta organización propone un modelo y funcionamiento desde los principios de la territorialidad, la autonomía, la identidad, la historia propia, la participación, la diversidad e interculturalidad, manifestada en la sociedad colombiana y las relaciones internacionales de los pueblos indígenas.');
